# ...existing code...
name: Databricks CI/CD

on:
  push:
    branches: [ main, master, release ]
  pull_request:

env: |
DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

jobs:
  staging:
    name: Validate in dev
    environment: dv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.295.0
        with:
          ref: ${{github.event.pull_request.head.sha || github.sha }}
      - run: databricks bundle validate -t dv
