name: Databricks Bundle Deploy

on:
  push:
    branches:
      - master
      
  pull_request:
    branches: 
      - master

defaults:
  run:
    working-directory: ./bundle_files/

jobs:
  dv-ci-validate:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://dbc-bc909f8e-ee32.cloud.databricks.com
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}   # 👈 set at job leve

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Bundle
        run: databricks bundle validate -t dv
        
  dv-deploy:
    needs: dv-ci-validate
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://dbc-bc909f8e-ee32.cloud.databricks.com
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}   
    if:  github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Bundle dv
        run: databricks bundle deploy -t dv

  staging-deploy:
    needs: dv-deploy
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://dbc-bc909f8e-ee32.cloud.databricks.com
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}   
    if:  github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Bundle staging
        run: databricks bundle deploy -t staging
        
  prod-deploy:
    needs: staging-deploy
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://dbc-bc909f8e-ee32.cloud.databricks.com
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}   
    if:  github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Bundle prod
        run: databricks bundle deploy -t prod
